### ISSUE TITLE
Tutorial 1-2

### ISSUE THREAD

**Issue by leahss** [kidscancode/pygame_tutorials#6]
Hi, this is my first time coding, and I'm trying to go through all of your tutorials but I'm stuck on the second one where a window comes up but without the green dot or black background. I wonder if you could take a look through my code and see what I'm doing wrong. Thanks!
Edit:  Here is the Gist link:  https://gist.github.com/leahss/06e4498ad6a08bbf91761c69c3b2e650

**Comment by cbscribe** [comment]
This program runs fine when I run it on my computer.

**Comment by leahss** [comment]
Thanks you for your reply, may I ask which version of Python and Pygame you are using? 
I'm using Python 2.7.17 and Pygame 1.9.1 on mac OS Mojave 10.14.5

**Comment by cbscribe** [comment]
Those are very old versions (Python 2 has officially ended support this year and Pygame 1.9.1 is from 2009). I'm using Python 3.7.4 (all my tutorials use Python 3, and have for many years) and Pygame 1.9.6

You should never use the Mac OS built-in Python. Not only is it out of date, because it's built-in you can't/shouldn't install or update additional packages.

Download homebrew from https://brew.sh/ and use it to install Python 3, then you can do `pip3 install pygame` to get the latest version.

**Comment by leahss** [comment]
Thank you so much for taking your time to help me out, it took me the whole day but finally it worked. After downloading and installing multiple versions of pip, python, homebrew, I finally got it to work. THANK YOU!
